### ISSUE TITLE
cant install python -m pip install heartpy(python -m pip install heartpy)

### ISSUE THREAD

**Issue by saranzeb** [paulvangentcom/heartrate_analysis_python#65] opened 2021-04-01 08:48 UTC
I can install in base environment  but not in virtual envs 
i have tried to install heartpy on windows gpu in virtual environment  with pytorch 1.6 but its showing SSL error although i can install it in base environment  
in virtual env i have to specify the python version instead of - m I think

**Comment by paulvangentcom** [comment] 2021-04-01 08:56
Can you provide a bit more info on the error you are getting, perhaps a screenshot?

**Comment by paulvangentcom** [comment] 2021-04-14 08:07
Closing this for now as I assume the problem is either solved or no longer actual. Feel free to reopen if you still need assistance

Paul

**Closed by paulvangentcom** 2021-04-14 08:07 UTC
